`timescale 1ns / 1ps

module spi_bist_top
#(parameter DATA_WIDTH =8,
  parameter ADDR_WIDTH =4,
  parameter WORD_COUNT =8,
  parameter TIMEOUT_VAL = 512,
  parameter [7:0] LFSR_SEED_VAL = 8'h01)
(//system
  input wire clk,//system clk
  input wire rst_n,//active low reset
 // host register write port
  input wire wr_en,//write enable
  input wire [ADDR_WIDTH-1:0] wr_addr,//register address
  input wire [15:0] wr_data,//this is tha data coming from cpu/tb
 // host register read port
 input wire [ADDR_WIDTH-1:0] rd_addr,//which register should be read
 output wire [15:0] rd_data,//register file return the selected register content
 //external SPI Pins
 output wire spi_sclk,//serial clk output
 output wire spi_mosi,//data trasmited to external spi device
 output wire spi_ss_n,//slave select
 input wire spi_miso,//data comng from external spi slave
 //debug
 output wire bist_pass_pulse,//produce pulse when bist pass
 output wire bist_fail_pulse  //produce pulse when bist fails
  );
  
//register file <-> spi master wires
wire cpol_w;//clk polarity
wire cpha_w;//clk phase
wire [7:0] clk_div_w;//clk divider
wire [DATA_WIDTH-1:0] tx_data_reg_w;//trasmit data from register file
wire spi_en_reg_w;//spi enable tell master to start transmission

wire [DATA_WIDTH-1:0] rx_data_m_w;//received data from master
wire busy_w;//spi busy flag
wire done_w;//spi done flag

//register file <-> bist controller wires
wire bist_en_w;//bist enable wire
wire bist_start_reg_w;//start command
wire [1:0] bist_mode_w;//bist test mode selection
wire [DATA_WIDTH-1:0] bist_sig_exp_w;//expected signature

wire bist_pass_w;
wire bist_fail_w;
wire bist_busy_w;
wire [3:0] err_code_w;//diagnostic error code

wire bist_start_qualified_w = bist_start_reg_w & bist_en_w;//start and enale both should be true

//bist controller <-> spi master wires
wire bist_spi_en_w;//spi enable signal generated by bist
wire [DATA_WIDTH-1:0] bist_tx_w;//data generated by bist ctrl
wire loopback_en_w;//bist mode or in normal mode

//if loopback en,spi en come from bist else come from register file
wire spi_en_to_master_w = loopback_en_w ? bist_spi_en_w : spi_en_reg_w;
//data that master transmit:- usiing condition from loopback_en
wire [DATA_WIDTH-1:0] tx_data_to_master_w = loopback_en_w ? bist_tx_w : tx_data_reg_w;

//bist controller <-> LFSR wires
wire lfsr_seed_load_w;//load seed now
wire lfsr_en_w;//Enable the LFSR to generate the next pattern.
wire [DATA_WIDTH-1:0] lfsr_data_w;//output of the lfsr

//bist controller <-> misr wires
wire misr_en_w;//enable misr to capture once rcvd byte
wire misr_rst_w;//reset the misr
wire [DATA_WIDTH-1:0] misr_sig_w;//current misr signature

//spi master <-> loopback mux
wire master_sclk_w;//spi clk generated by spi master
wire master_mosi_w;//mastr out slave in
wire master_ss_n_w;//slave select
wire master_miso_w;//rcvd by spi master

//loopback MUX <-> internal spi slave wires
wire slave_sclk_w;//clk input of the internal spi slave
wire slave_mosi_w;//mosi input of the internal spi slave
wire slave_ss_n_w;//slave select for internal spi slave
wire slave_miso_w;//data transmited by internal spi slave
wire [DATA_WIDTH-1:0] slave_rx_data_w;//complete byte received by the SPI Slave.
wire slave_rx_done_w;//Receive Complete Flag

// debug pulse pass-through
assign bist_pass_pulse = bist_pass_w;
assign bist_fail_pulse = bist_fail_w;

//reg file instance
spi_regfile #(
    .DATA_WIDTH (DATA_WIDTH),
    .ADDR_WIDTH (ADDR_WIDTH)
) u_regfile (
    .clk             (clk),
    .rst_n           (rst_n),
 
    .wr_en           (wr_en),
    .wr_addr         (wr_addr),
    .wr_data         (wr_data),
    .rd_addr         (rd_addr),
    .rd_data         (rd_data),
 
    .spi_en_out      (spi_en_reg_w),
    .cpol            (cpol_w),
    .cpha            (cpha_w),
    .clk_div         (clk_div_w),
    .tx_data         (tx_data_reg_w),
 
    .rx_data_in      (rx_data_m_w),
    .busy_in         (busy_w),
    .done_in         (done_w),
 
    .bist_en         (bist_en_w),
    .bist_start_out  (bist_start_reg_w),
    .bist_mode       (bist_mode_w),
    .bist_sig_exp    (bist_sig_exp_w),
 
    .bist_pass_in    (bist_pass_w),
    .bist_fail_in    (bist_fail_w),
    .bist_sig_act_in (misr_sig_w),
    .err_code_in     (err_code_w)
);
 
//spi master instance
spi_master #(
    .DATA_WIDTH (DATA_WIDTH)
) u_master (
    .clk      (clk),
    .rst_n    (rst_n),
 
    .spi_en   (spi_en_to_master_w),   // Decision 1: muxed source
    .cpol     (cpol_w),
    .cpha     (cpha_w),
    .clk_div  (clk_div_w),
 
    .tx_data  (tx_data_to_master_w),  // Decision 1: muxed source
    .rx_data  (rx_data_m_w),
 
    .busy     (busy_w),
    .done     (done_w),
 
    .sclk     (master_sclk_w),
    .mosi     (master_mosi_w),
    .ss_n     (master_ss_n_w),
    .miso     (master_miso_w)
);

//loopback mux
loopback_mux u_loopback_mux (
    .loopback_en (loopback_en_w),
 
    .m_sclk      (master_sclk_w),
    .m_mosi      (master_mosi_w),
    .m_ss_n      (master_ss_n_w),
    .m_miso      (master_miso_w),
 
    .ext_sclk    (spi_sclk),
    .ext_mosi    (spi_mosi),
    .ext_ss_n    (spi_ss_n),
    .ext_miso    (spi_miso),
 
    .slv_sclk    (slave_sclk_w),
    .slv_mosi    (slave_mosi_w),
    .slv_ss_n    (slave_ss_n_w),
    .slv_miso    (slave_miso_w)
);

//internal spi slave(bist loopback target)
spi_slave #(
    .DATA_WIDTH (DATA_WIDTH)
) u_slave (
    .clk      (clk),
    .rst_n    (rst_n),
 
    .cpol     (cpol_w),
    .cpha     (cpha_w),
 
    .sclk_in  (slave_sclk_w),
    .mosi     (slave_mosi_w),
    .miso     (slave_miso_w),
    .ss_n_in  (slave_ss_n_w),
 
    .tx_data  (bist_tx_w),            // Decision 2: zero-latency echo
    .rx_data  (slave_rx_data_w),
    .rx_done  (slave_rx_done_w)
);

//bist controller
bist_ctrl #(
    .DATA_WIDTH  (DATA_WIDTH),
    .WORD_COUNT  (WORD_COUNT),
    .TIMEOUT_VAL (TIMEOUT_VAL)
) u_bist_ctrl (
    .clk            (clk),
    .rst_n          (rst_n),
 
    .bist_start     (bist_start_qualified_w),  // Decision 3: AND-gated
    .bist_mode      (bist_mode_w),
    .bist_sig_exp   (bist_sig_exp_w),
 
    .bist_pass      (bist_pass_w),
    .bist_fail      (bist_fail_w),
    .bist_busy      (bist_busy_w),
    .err_code       (err_code_w),
 
    .spi_en         (bist_spi_en_w),
    .spi_done       (done_w),
    .rx_data        (rx_data_m_w),
    .bist_tx        (bist_tx_w),
 
    .lfsr_seed_load (lfsr_seed_load_w),
    .lfsr_en        (lfsr_en_w),
    .lfsr_data      (lfsr_data_w),
 
    .misr_en        (misr_en_w),
    .misr_rst       (misr_rst_w),
    .misr_sig       (misr_sig_w),
 
    .loopback_en    (loopback_en_w)
);

//lfsr pattern generator
 lfsr #(
    .DATA_WIDTH   (DATA_WIDTH),
    .DEFAULT_SEED (LFSR_SEED_VAL)
) u_lfsr (
    .clk       (clk),
    .rst_n     (rst_n),
 
    .seed_load (lfsr_seed_load_w),
    .seed_in   (LFSR_SEED_VAL),        // Decision 4: fixed golden-matching seed
 
    .en        (lfsr_en_w),
    .lfsr_data (lfsr_data_w)
);

//MISR SIG Analyzer
misr #(
    .DATA_WIDTH (DATA_WIDTH)
) u_misr (
    .clk      (clk),
    .rst_n    (rst_n),
 
    .misr_rst (misr_rst_w),
    .misr_en  (misr_en_w),
    .data_in  (rx_data_m_w),           // Master's received byte (loopback)
 
    .sig_out  (misr_sig_w)
);
  
endmodule
